##############################################################################
#                          Basic Charts Collections                          #
#                 Created by Yozora, Bullmoose20, & Sohjiro                  #
#          EDITING THIS FILE MAY CAUSE PULLING NEW UPDATES TO FAIL           #
#        https://metamanager.wiki/en/latest/defaults/chart/basic.html        #
##############################################################################

external_templates:
  default: templates
  template_variables:
    collection_section: "01"
    image: chart/<<collection_name_encoded>>
  repo: metadata/mytemplates.yml  

collections:

  Dernières sorties:
    variables:
      key: released
    template:
      - name: shared      
    smart_label: release.desc    
    trakt_list: https://trakt.tv/users/pierredurrr/lists/best-new-movies?sort=rank,asc
    filters:
      filepath:
        - /mnt/_SYNOLOGY/video/_Latest_Releases    

#  New Episodes:
#    variables:
#      key: episodes
#    template:
#      - name: smart_filter
#        search_term: episode_air_date
#        search_value: <<in_the_last_episodes>>
#        in_the_last_episodes: 7
#        type: episodes
#      - name: shared
#        allowed_libraries: show
#      - name: translation
#        translation_key: basic_episodes
